* "Ethics in Bioimaging amd Bioinformatics in Medicine" essay quotes and notes
*NOTE :- ANYTHING IN QUOTATION MARKS IS A DIRECT QUOTE. CONSIDER REPHRASING*
*Ticks mean I quoted something*

** Ethics, Computing and Genomics [Book] By Herman T. Tavani (link [[https://books.google.co.uk/books?id%3DwlrPaPRshesC&lpg%3DPP4&pg%3DPA320#v%3Donepage&q&f%3Dfalse][here]])
tavani2006ethics
*** Chapter 17 - Bioinformatics: Bioinformatics: Challenges at the Frontier
- [X] "Information Technology and genetics are the sciences that will have the greatest effect on 21st century healthcare"
- [X] "Bioinformatics...the use of information technology to acquire, store, manage, share, analyze represent and transmit genetic data, has blossomed in the past decade."
**** Accuracy and Error
- [ ] need to ensure accuracy and error avoidance - ethical issue
- [ ] "The reason to link error and ethics is that errors, however unintentional, can lead to harms. Whether a harm constitutes a wrong is one of the main challenges of morality"
- [ ] "Risk to persons"
  + [ ] computer aided loci identification- faster /ergo/ - more frequent errors
  + [ ] psychological risks in predicting future illnesses - *important* have /genetic counsellors/
- [ ] "Recanted linkage studies"
  + [ ] sometimes, linkage studies unreplicated and have to be recanted
  + [ ] linkage that correlates with particular races/ethnic groups can have stigma attached
    * [ ] espesc. w.r.t neurogenetic/psychiatric genetics
- [ ] Meta-analysis - important to introduce doubts from linkage studies
- [ ] "Decision support" - raise ethical issues
  + [ ] Isn't yet (2006) any critical analysis of decision support for use of clinical information, photographic material, pedigree and gene localization evaluation by computer
    * [ ] MIller and Goodman suggest ripe for inquiry (Ethics, Computing, and Medicine - Kenneth W. Goodman, 1998)
- [ ] "Appropriate Uses and Users"
  + [ ]  who should be using these information systems with clinical information
  + [ ] should seek consent of patient for each 'novel use' of data
  + [ ] access by doctors/nurses unskilled in area of diagnosis using this data should not be allowed access to this data
- [ ] Privacy and Confidentiality
  + [ ] need appropriate authorisation of access to data
  + [ ] prevent inappropriate / unauthorised access
  + [ ] personal data can have stigma attached to it
    * [ ] problems well explored w.r.t *electronic patient record*
    * (see /Albert 1998/)


** TODO Ethics, Computing, And Medicine [Book] By Kenneth W. Goodman (link [[https://books.google.co.uk/books?id%3DWb6apuz7_ocC&lpg%3DPA24&ots%3DD21gsvzxbR&dq%3DMiller%252C%2520Goodman%25201998%2520-Miller-Goodman&lr&pg%3DPP1#v%3Donepage&q%3DMiller,%2520Goodman%25201998%2520-Miller-Goodman&f%3Dfalse][here]])


** Ethics of Bioinformatics: A Convergence between Bioethics and Computer Ethics
hongladarom2006ethics
*** Bioinformatics
- Manipulating genetic data
- [X] Privacy greatest concern
- [X] Is ethics of Bioinformatics BioEthics or Computer Ethics - can view from multiple perspectives
- [X] "Towards an Ethics of Bioinformatics"
  + [X] Stealing genetic data - more serious than stealing credit card number
    * identity theft - stealing a real part of your identity
  + [X] Genetic sequence unique part of your identity. Credit card number. Therefore is a big part of one's identity and thus should ethically be treated with much more care than a credit card number.


** Japan's bioinformatics efforts misguided
triendl2001japan
- [ ] Japan Biological Informatics Consortium (JBIC) felt clinical use of bioinformatics was premature in 2001
- [ ] Country was unprepared for clinical genetic research
- [ ] Jiro Nudeshima, bioethics specialist
  + [ ]  There weren't any guidelines for genetic testing
  + [ ] Rarely find counseling for patients who went through genetic testing
  + [ ] procedures for informed consent were inadequate


** Integrating biobanks: addressing the practical and ethical issues to deliver a valuable tool for cancer research
watson2010integrating
- [X] personalised medicine lead to departure from 'one-size fits all' treatment of cancer
  + [X] imatinib - target specific subpopulation in chronic myeloid leukaemia ([[https://clincancerres.aacrjournals.org/content/8/5/935.full.pdf%2Bhtml][link]])
  + [X] herceptin - ERBB2-positive ([[http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2768514/][link]])
- [ ] This could lower costs of clinical trials and improve identification of biomarkers
- [ ] for this, need biobanks - important resource for understanding underlying cause of cancer
- [ ] clear guidelines required to integrate individual institutions with national biobanks all while building public trust
- [-] "Ethical issues associated with integration"
  + [ ] "Patient Consent"
    * [ ] Best systems educate users and allow them to choose what kind of trials their data is included in
    * [ ] however, increasing pressure with regard for increasing flexibility to use sample data
    * [ ] ARGUMENT: unlike clinical trials, it isn't hurting anyone ergo, should be less stringent with this data?
    * [ ] However, "To what extent can such consent about the unknown future be accurately described as informed consent?"
    * [ ] Could rectify this by allowing patients to withdraw their data from a biobank whenever new research projects are authorised by an Institution Review Board
  + [ ] Right of individuals to remove their data from biobank
    * [ ] participants have right to remove data from biobank in accordance with Nuremberg Code and the declaration of Helsinki
    * [ ] However, this is not in the interest of industry/research as it can affect the statistical integrity of data
    * [ ] UK Biobank has graded withdrawal:
      - [ ] complete withdrawal
      - [ ] discontinued participation
      - [ ] no further contact
  + [-] Role of IRBs (Institution Review Boards) and RECs (Research Ethics Committees)
    * [X] consent from IRBs and RECs necessary to use biobank materials
    * [ ] ensure seek consent with narrowly worded permission of usage
    * [ ] becoming the "Guardians of biobanks" as time moves on


** Simplifying informed consent for biorepositories: Stakeholder perspectives
beskow2010simplifying
- [X] Obtaining consent in biobanking complicated/controversial
- [X] consent forms perceptively getting longer and more complicated
- [X] Did a study where they created a sample biorepository consent form
  + [X] Asked patients, IRB staff and researchers to underline lines they felt important to ask on the consent form
  + [X] IRB staff hilighted most lines, Researchers less and patients least
    * [X] A THOUGHT: Can patients be trusted to know the implications of submitting their data to a biobank
  + [X] Top ranked sentences not similar between groups - maybe because each of the groups have different motivations?
    * [X] researchers only want to maximise number of participants
    * [X] IRB there to protect participants
  + [X] There is hope - the article presented was written at an 8th grade reading level
  + [X] HOWEVER, IMHO, participants in study weren't asked if consent form had gaps in it.


**  Considering something 'ELSE': Ethical, legal and socio-economic factors in medical imaging and medical informatics
duquenoy2008considering
- research driven by technological advances
- [ ] must also consider ELSE (Ethical, Legal and Socio-Economic implications)
- [ ] One such technology - Medical Imaging and Medical Informatics (MIMI)
- [ ] context is that of computer scientists within "principles of governance" set out by healthcare professionals
  + [ ] need to bridge gap between ethical considerations and technological progress
- [ ] "electronic medical data"
  + [ ] Patient I.D
  + [ ] recorded symptoms
  + [ ] diagnosis
  + [ ] treatment
  + [ ] relevant supporting evidence (e.g. medical images -TMA image poss)
- [ ] Ethical duties put forward by (Beauchamp and Childress, 2001)
  + [ ] Beneficence
  + [ ] Non-malefeasance
  + [ ] Autonomy
  + [ ] Justice
- [-] Ethical issues in IT field
  + [ ] normally to do with protection of private individuals personal data
  + [X] this article takes it that medical images is a form of personal data
  + [ ] must protect individuals personal data but also the ways in which it is examined and interpreted
- [ ] Law places responsibility on people to keep confidential information that they know is to be treated as confidential
  + [ ] Obviously, Medical data should be treated as confidential
  + [ ] third parties accidentaly receiving data that should be confidential also has duty of confidence


** TODO Avoiding Twisted Pixels Ethical Guidelines...
cromey2010avoiding
- [ ]

** TODO Digital Images are Data: And Should Be Treated as Such
cromey2013digital

** TODO From genetic privacy to open consent
lunshof2008genetic


** TODO Data sharing in genomics — re-shaping scientific practice
kaye2009data


** TODO Next-generation sequencing in the clinic: are we ready?
biesecker2012next


** TODO Genetic research and stored biological materials: ethics and practice
wolf2010genetic
